export const CREATE_DISCOUNT_REQUEST = "CREATE_DISCOUNT_REQUEST";
export const CREATE_DISCOUNT_SUCCESS = "CREATE_DISCOUNT_SUCCESS";
export const CREATE_DISCOUNT_FAILURE = "CREATE_DISCOUNT_FAILURE";

export const ON_FORM_FIELD_CHANGE = "ON_FORM_FIELD_CHANGE";

export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

export const GET_DISCOUNT_REQUEST = "GET_DISCOUNT_REQUEST";
export const GET_DISCOUNT_SUCCESS = "GET_DISCOUNT_SUCCESS";
export const GET_DISCOUNT_FAILURE = "GET_DISCOUNT_FAILURE";

export const GET_DISCOUNTS_REQUEST = "GET_DISCOUNTS_REQUEST";
export const GET_DISCOUNTS_SUCCESS = "GET_DISCOUNTS_SUCCESS";
export const GET_DISCOUNTS_FAILURE = "GET_DISCOUNTS_FAILURE";

export const GET_GROUP_DISCOUNT_REQUEST = "GET_GROUP_DISCOUNT_REQUEST";
export const GET_GROUP_DISCOUNT_SUCCESS = "GET_GROUP_DISCOUNT_SUCCESS";
export const GET_GROUP_DISCOUNT_FAILURE = "GET_GROUP_DISCOUNT_FAILURE";